CREATE TABLE COMERCIAL (
DNI VARCHAR2(9)CONSTRAINT COMERCIAL_PK PRIMARY KEY,
NOMBRE VARCHAR2(50) NOT NULL,
APELLIDOS VARCHAR2 (100),
FECHA_NACIMIENTO DATE,
BONIFICACION VARCHAR2 (200),
TITULACION VARCHAR2 (100),
ID_DEPARTAMENTO NUMBER (10),
ID_SUCURSAL NUMBER (10)
);
CREATE TABLE PROGRAMADOR (
DNI VARCHAR2(9) CONSTRAINT PROGRAMADOR_PK PRIMARY KEY,
NOMBRE VARCHAR2(50)NOT NULL,
APELLIDOS VARCHAR2 (100),
FECHA_NACIMIENTO DATE,
LENGUAJES VARCHAR2 (10),
PUESTO VARCHAR2 (50),
ID_DEPARTAMENTO NUMBER (10),
ID_SUCURSAL NUMBER (10)
);
CREATE TABLE DEPARTAMENTO (
ID_DEPARTAMENTO NUMBER (10),
ID_SUCURSAL NUMBER (10),
NOMBRE VARCHAR2(50) NOT NULL,
DIRECCION VARCHAR2 (50),
CONSTRAINT DEPARTAMENTO_PK PRIMARY KEY (ID_DEPARTAMENTO,ID_SUCURSAL)
);
CREATE TABLE SUCURSAL (
ID_SUCURSAL NUMBER (10)CONSTRAINT SUCURSAL_PK PRIMARY KEY,
NOMBRE VARCHAR2 (50),
DIRECCION VARCHAR2 (50)
);
CREATE TABLE PROYECTO(
COD_PROYECTO VARCHAR2(10) CONSTRAINT PROYECTO_PK PRIMARY KEY,
NOMBRE VARCHAR2 (50),
DESCRIPCION VARCHAR2 (50),
ID_DEPARTAMENTO NUMBER (10),
ID_SUCURSAL NUMBER (10)
);
CREATE TABLE PROYECTO_CLIENTE(
COD_PROYECTO NUMBER (10),
ID_CLIENTE NUMBER (10),
CONSTRAINT PROYEC_CLIENT_PK PRIMARY KEY (COD_PROYECTO, ID_CLIENTE)
);
CREATE TABLE CLIENTE(
ID_CLIENTE NUMBER(10) CONSTRAINT CLIENTE_PK PRIMARY KEY,
NOMBRE VARCHAR2 (50),
TELEFONO NUMBER (9) UNIQUE,
DIRECCION VARCHAR2 (50),
EMAIL VARCHAR2 (100) UNIQUE
);

ALTER TABLE COMERCIAL  ADD CONSTRAINT COMERCIAL_FK FOREIGN KEY (ID_DEPARTAMENTO, ID_SUCURSAL) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO, ID_SUCURSAL);
ALTER TABLE PROGRAMADOR  ADD CONSTRAINT PROGRAMADOR_FK FOREIGN KEY (ID_DEPARTAMENTO, ID_SUCURSAL) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO, ID_SUCURSAL);
ALTER TABLE DEPARTAMENTO  ADD CONSTRAINT DPTO_FK FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL (ID_SUCURSAL);
ALTER TABLE PROYECTO  ADD CONSTRAINT PROYECTO_FK FOREIGN KEY (ID_DEPARTAMENTO, ID_SUCURSAL) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO, ID_SUCURSAL);
ALTER TABLE PROYECTO_CLIENTE MODIFY COD_PROYECTO VARCHAR2(10);
ALTER TABLE PROYECTO_CLIENTE  ADD CONSTRAINT PROYECTO_CLIENT_FKPROYECT FOREIGN KEY (COD_PROYECTO) REFERENCES PROYECTO (COD_PROYECTO);
ALTER TABLE PROYECTO_CLIENTE  ADD CONSTRAINT PROYECTO_CLIENT_FKPCLIENT FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE);

ALTER TABLE PROGRAMADOR ADD CONSTRAINT LENGUAJES_CK CHECK (LENGUAJES IN('JAVA','PHP','SQL','ANDROID'));
